FROM python:3.11-slim

WORKDIR /app

COPY scripts/getdata_weatherAPI.py /app
COPY scripts/requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "getdata_weatherAPI.py"]